version: '3.1'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: task-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  postgres-data:
